---
# tasks file for makkus.workstation

- name: "Generate ssh key"
  command: ssh-keygen -N "{{ ssh_key_password }}" -f "~/.ssh/id_rsa" creates=~/.ssh/id_rsa
  tags:
    - workstation
    - workstation:user
    - workstation:ssy_key
  become: no

- name: "Upload ssh key to github"
  shell: curl -u "makkus:{{ github_password }}" --data "{\"title\":\"$(hostname)\", \"key\":\"$(cat /home/markus/.ssh/id_rsa.pub)\"}" https://api.github.com/user/keys
  tags:
    - workstation
    - workstation:user
    - workstation:github

- name: "Create gnupg dir"
  file: path="~/.gnupg"
  tags:
    - workstation
    - workstation:user
  become: no

- name: "Setup gpg public keys"
  copy: src={{ data_external }}/gpg/pubring.gpg dest=~/.gnupg/pubring.gpg mode=0600 force=no
  tags:
    - workstation
    - workstation:user
  become: no

- name: "Setup gpg private keys"
  copy: src={{ data_external}}/gpg/secring.gpg dest=~/.gnupg/secring.gpg mode=0600 force=no
  tags:
    - workstation
    - workstation:user
  become: no

- name: import ownertrust
  command: gpg --import-ownertrust {{ data_external }}/gpg/markus-ownertrust.gpg.txt creates=~/.gnupg/trustdb.gpg
  tags:
    - workstation
    - workstation:user
  become: no

